### ISSUE TITLE
What's the license on these packages?

### ISSUE THREAD

**Issue by aateeque** [gep13-oss/ChocolateyPackages#9]
Specifically the cake scripts at https://github.com/gep13/ChocolateyPackages/tree/master/gep13.DefaultBuild

**Comment by gep13** [comment]
@aateeque apologies for not having the license listed on this repo. That particular package is in this repo for convenience more than anything else. Ultimately, it will be released under an MIT license, and it will likely move under the cake-control organisation on GitHub.
